language: objective-c

env:
  global:
    - EnableNuGetPackageRestore=true
  matrix:
    - MONO_VERSION="5.4.0"

install:
  - wget "https://download.mono-project.com/archive/${MONO_VERSION}/macos-10-universal/MonoFramework-MDK-5.4.0.201.macos10.xamarin.universal.pkg"
  - sudo installer -pkg "MonoFramework-MDK-5.4.0.201.macos10.xamarin.universal.pkg" -target /
  - chmod 755 ./build.sh

script: 
  - ./build.sh AllCore
  
branches:
  except:
    - gh-pages
    - release
  