language: csharp

sudo: required
dist: trusty

matrix:
  include:
    - mono: latest
      dotnet: 2.1.302
      env: USE_MSBUILD=1
      os: linux
    - mono: latest
      dotnet: 2.1.302
      os: linux

before_install:
  - chmod +x build.sh
 
script: 
  - ./build.sh AllCore
  
branches:
  except:
    - gh-pages
    - release