language: objective-c

env:
  global:
    - EnableNuGetPackageRestore=true
  matrix:
    - MONO_VERSION="3.8.0"

install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - chmod 755 ./build.sh

script: 
  - ./build.sh AllCore
  
branches:
  except:
    - gh-pages
    - release
  
